server.port=8092
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomind
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CORS allowed origins for development (includes localhost).
cors.allowed-origins=https://ecomind-app.web.app,http://localhost:4200,http://localhost:5173

culqi.api.base-url=https://api.culqi.com/v2
culqi.api.secret-key=${CULQI_SECRET_KEY:sk_test_4cyXDRCpwQ5JTs0l}
culqi.api.public-key=${CULQI_PUBLIC_KEY:pk_test_Z2WRdxu0EQOGU2Ge}

paypal.api.base-url=https://api-m.sandbox.paypal.com
paypal.api.client-id=${PAYPAL_CLIENT_ID:AUmHZeDzviWVJj_rnXU_c5wEhRKANH7yy_HFdJVDWxgsc1lX_8xYrfG0NJqLJHynBKAsXy4YsaIzZeh2}
paypal.api.secret=${PAYPAL_SECRET:EJBhCVHItagDytL2QXLGKOmz-j7KnLoBZR8inzsTMBgCRG1nt2IYHiM6vumi_czn_K-6WjFx3abRm1Zr}
