spring.application.name=ecomind-backend
spring.profiles.active=dev

spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=pe.greenminds.ecomind_backend.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

spring.devtools.restart.enabled=false

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.always-use-message-format=true
spring.messages.fallback-to-system-locale=false

documentation.application.description=API de Ecomind
documentation.application.version=1.0.0
